swagger: "2.0"
info:
  title: Image Upload API
  description: API for uploading images to AWS S3
  version: "1.0"

basePath: /api/images
schemes:
  - http

paths:
  /upload:
    post:
      summary: Upload an image
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: image
          type: file
          required: true
          description: The image file to upload
      responses:
        201:
          description: Image uploaded successfully
        400:
          description: No image provided
        500:
          description: Internal server error
